### ISSUE TITLE
3.1 Constructorの修正

### ISSUE THREAD

**Issue by ptr-yudai** [kosen14s/Yurufuwa-PaymentRequestAPI#17]
仕様書とかプログラムとか詳しくないので、必要と思う箇所だけ修正してください。

■主要な部分
修正前：
PaymentRequest は、渡された methodData リスト（決済方法固有のデータを含む）、決済の詳細、決済オプションによって構成されます。 PaymentRequest コンストラクタに渡された methodData は、呼び出し元の優先度（プリファレンス）順に並んでいる必要があります。
NOTE: methodData シーケンスは PaymentMethodData dictionaries をもち、それはウェブサイトが許可する決済方法のための識別子 payment method identifiers 及び関連する決済方法固有のデータをもちます。
修正後：
PaymentRequest は、渡される決済方法(payment method)の詳細データを含む methodData リスト、決済の詳細(details)、および決済オプションを使って構成されます。PaymentRequest コンストラクタに渡された methodData は呼び出し元の優先度順に並んでいるべきです。
NOTE: methodData シーケンスは、ウェブサイトが許容する決済方法(payment method)の識別子(payment method identifiers)を持つ PaymentMethodData ディクショナリ、ならびに決済方法(payment method)の詳細データを保持します。
備考：
直接的にはPaymentMethodDataディクショナリが識別子を持っている。
次の文では"details"をそのまま記述していたので括弧内に記述。
specific dataはここでは「詳細なデータ」が妥当？

修正前：
PaymentRequest(methodData, details, options) コンストラクタは次のように振る舞うべきです。
修正後：
PaymentRequest(methodData, details, options) コンストラクタは次のように振る舞う必要があります。

修正前：
paymentMethod が存在するとき serializedData は paymentMethod.data をJSONシリアライズした結果（文字列）にします。存在しなければ null を返し、何か例外を投げます。
修正後：
paymentMethod の data メンバが存在するときは serializedData を paymentMethod.data をJSONシリアライズした結果（文字列）にし、そうでない場合は null にします。例外があれば再スローしてください。
備考：
dataメンバの追加。もしくはそれ以降に現れる同様の表現に沿うなら「paymentMethod.data が存在するとき」。
「返し」というのが伝わりにくいかもです。
anyはたぶん「あったら」という感じ？

修正前：
options を空のシーケンス にします。
修正後：
options を空のシーケンス \<PaymentShippingOption\> にします。
備考：
マークダウンの記法で表示されてないだけです。
同様に「modifiers を空のシーケンス にします。」のところも直しておいてください。

修正前：
option.selected が true なら、option.id に selectedShippingOption をセットします。
修正後：
option.selected が true なら、selectedShippingOption を option.id にセットします。
備考：
"set A to B"のとき、「A <-- B」であることを明確に。
本当は「AをBにします」とした方が良いかもです。

修正前：
details.modifiers に modifiers をセットします。
修正後：
modifiers を details.modifiers にセットします。

修正前：
additionalDisplayItems が存在するとき、 modifier.additionalDisplayItems のそれぞれについて
修正後：
modifier.additionalDisplayItems が存在するとき、 modifier.additionalDisplayItems のそれぞれについて

修正前：
serializedData は modifier.data をJSONシリアライズした結果（文字列）にします。存在しなければ null を返し、何か例外を投げます。
修正後：
modifier.data が存在するとき、serializedData は modifier.data をJSONシリアライズした結果（文字列）にし、存在しなければ null にします。例外があれば再スローしてください。

修正前：
modifiers に details.modifiers をセットします。
修正後：
details.modifiers を modifiers にセットします。

修正前：
selectedShippingOption に request の shippingOption 属性の値をセットします。
修正後：
request の shippingOption 属性値を selectedShippingOption にセットします。

修正前：
request の shippingType を null にします。
修正後：
options.requestShippingがtrueであれば、request の shippingType 属性の値に option.shippingType をセットします。trueでない場合は null をセットします。

■細かい部分
修正前：
もし details.id が無ければ details に id を追加し、...
修正後：
もし details.id が無ければ details に id メンバを追加し、...
備考：
同様に「modifier に total が存在するとき」も「modifier に total メンバが存在するとき」に直せます。

修正前：
最低一つの payment method が必要であることを...
修正後：
最低一つの決済方法(payment method)が必要であることを...
備考：
今までは"payment method"を「決済方法」と訳していたので。

**Comment by theoremoon** [comment]
こんなん pull req だせばええんやで

**Comment by yamasy1549** [comment]
めっちゃありがとう 🙏 
clone とか不要でブラウザからも pull req 出せるので気になるところどんどん指摘ほしいです！

**Comment by theoremoon** [comment]
#18
